version: '3.8'

services:
  zwave:
    image: ghcr.io/msazanov/amd64-ha-z-wave-me-addon:main
    #build: .
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "./data:/data"
    ports:
      - "8083:8083"
    restart: unless-stopped
